org: stampingio
service: api-pelicula

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::762233757087:role/lab-role

functions:
  crear:
    handler: CrearPelicula.lambda_handler
    events:
      - http:
          path: /pelicula/crear
          method: post
          cors: true
          integration: lambda

resources:
  Resources:
    TABLAPELICULA:  # Cambié el nombre de la tabla a TABLAPELICULA
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TABLAPELICULA  # Fijo el nombre de la tabla como TABLAPELICULA
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: uuid
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

